import os

db_config = {
    "host": "localhost",
    "username": "root",
    "password": "63130500059",
    "db": "vocaverse",
    "port": "3306"
}

tables_name = {"vocabulary": "vocabulary"}

datasources_path = "datasources"
completed_file_path = os.path.join(
    os.path.abspath(datasources_path),
    f"computed_file.csv",
)

pos = {
    "ADJ": "Adjective",
    "ADP": "Adposition",
    "ADV": "Adverb",
    "AUX": "Auxiliary verb",
    "CONJ": "Coordinating conjunction",
    "DET": "Determiner",
    "INTJ": "Interjection",
    "NOUN": "Noun",
    "NUM": "Numeral",
    "PART": "Particle",
    "PRON": "Pronoun",
    "PROPN": "Proper noun",
    "PUNCT": "Punctuation",
    "SCONJ": "Subordinating conjunction",
    "SYM": "Symbol",
    "VERB": "Verb",
    "X": "Other",
}

included_pos = {
    "ADJ": "Adjective",
    "ADP": "Adposition",
    "ADV": "Adverb",
    "AUX": "Auxiliary verb",
    "CONJ": "Coordinating conjunction",
    "DET": "Determiner",
    # 'INTJ': 'Interjection',
    "NOUN": "Noun",
    # 'NUM': 'Numeral',
    # 'PART': 'Particle',
    "PRON": "Pronoun",
    "PROPN": "Proper noun",
    "PUNCT": "Punctuation",
    "SCONJ": "Subordinating conjunction",
    "SYM": "Symbol",
    "VERB": "Verb",
    # 'X': 'Other'
}

pos_more_tags = {
    "NN": "Noun, singular or mass",
    "NNS": "Noun, plural",
    "NNP": "Proper noun, singular",
    "NNPS": "Proper noun, plural",
    "VB": "Verb, base form",
    "VBD": "Verb, past tense",
    "VBG": "Verb, gerund or present participle",
    "VBN": "Verb, past participle",
    "VBP": "Verb, non-3rd person singular present",
    "VBZ": "Verb, 3rd person singular present",
    "JJ": "Adjective",
    "JJR": "Adjective, comparative",
    "JJS": "Adjective, superlative",
    "RB": "Adverb",
    "RBR": "Adverb, comparative",
    "RBS": "Adverb, superlative",
    "PRP": "Personal pronoun",
    "PRP$": "Possessive pronoun",
    "DT": "Determiner",
    "IN": "Preposition or subordinating conjunction",
    "CC": "Coordinating conjunction",
    "CD": "Cardinal number",
    "MD": "Modal",
}

dependency_relations = {
    "ROOT": "The root of the sentence, typically the main verb.",
    "acl": "A clausal modifier of a noun, adjective, or adverb.",
    "acomp": "Adjectival complement.",
    "advcl": "Adverbial clause modifier.",
    "advmod": "Adverbial modifier.",
    "agent": "Agent of passive verb.",
    "amod": "Adjectival modifier.",
    "appos": "Appositional modifier.",
    "attr": "Attribute.",
    "aux": "Auxiliary.",
    "auxpass": "Auxiliary (passive).",
    "case": "Case marker.",
    "cc": "Coordinating conjunction.",
    "ccomp": "Clausal complement.",
    "compound": "Compound.",
    "conj": "Conjunct.",
    "csubj": "Clausal subject.",
    "csubjpass": "Clausal subject (passive).",
    "dative": "Dative.",
    "dep": "Unclassified dependent.",
    "det": "Determiner.",
    "dobj": "Direct object.",
    "expl": "Expletive.",
    "intj": "Interjection.",
    "mark": "Marker.",
    "meta": "Meta modifier.",
    "neg": "Negation modifier.",
    "nmod": "Nominal modifier.",
    "npadvmod": "Noun phrase adverbial modifier.",
    "nsubj": "Nominal subject.",
    "nsubjpass": "Nominal subject (passive).",
    "nummod": "Numeric modifier.",
    "oprd": "Object predicate.",
    "parataxis": "Parataxis.",
    "pcomp": "Prepositional complement.",
    "pobj": "Object of a preposition.",
    "poss": "Possession modifier.",
    "preconj": "Pre-correlative conjunction.",
    "predet": "Predeterminer.",
    "prep": "Prepositional modifier.",
    "prt": "Particle.",
    "punct": "Punctuation.",
    "quantmod": "Quantifier modifier.",
    "relcl": "Relative clause modifier.",
    "xcomp": "Open clausal complement.",
}
